[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
